### ISSUE TITLE
Fuzzy text in Firefox

### ISSUE THREAD

**Issue by sujato** [DhammaCharts/suttapitaka-chart#1]
In Firefox (ubuntu 22.04, FF 100) the image doesn't resolve to enough detail, so the text is fuzzy, bordering on unreadable.

![Screenshot from 2022-05-29 10-24-17](https://user-images.githubusercontent.com/6112010/170846997-08ef68c7-077e-4986-8eae-57d28e77a90a.jpg)

**Comment by DhammaCharts** [comment]
Ok, interesting. On Firefox 100.0.2 on mac I don't have this issue it seems.

One thing about OpenLayers is that it will load the next level of tiles only when you reach the appropriate level of zoom. Compare to leaflet.js (see this [demo](https://leafletjs.com/index.html) for exemple) that doesn't allow intermediate levels of zoom, i.e. the zoom levels are only allowed between discret levels corresponding to tile layers, OpenLayers prefers to allow smooth zoom transition with slight "blurryness". Sometimes, on OpenLayers, if you zoom just slightly more, the next level of tiles will load.

Can you try https://openlayers.org/en/latest/examples/accessible.html on your firefox to see if you get the same result ?

**Comment by DhammaCharts** [comment]
I see also that the UI buttons are different on your screen shots. this is due to :

`<meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">` in `<head>` I believe.

I've added this line to be able to have descent popup size on mobile, but it makes the image more blurry on iPhone, I thought it was because of a resolution specific to iPhone, but I might be wrong.

**Comment by DhammaCharts** [comment]
I've haded `pixelRatio: 1` to the layers. Is there a difference ?

**Comment by DhammaCharts** [comment]
I tested on Linux mint Firefox 99.0.1 and it looks fine, as well as on ubuntu.
